

export const BREAKPOINTS = {
    smallScreen: 550,
    medScreen: 1100,
    bigScreen: 1500,
  }
  
export const QUERIES = {
    'smallerThanTablet': `(max-width: ${BREAKPOINTS.smallScreen}px)`,
    'smallerThanLaptop': `(max-width: ${BREAKPOINTS.medScreen}px)`,
    'smallerThanDesktop': `(max-width: ${BREAKPOINTS.bigScreen}px)`,
  }

export const NAME_ASCII = `
  ██████╗██╗  ██╗██████╗ ██╗███████╗    ███╗   ███╗██╗   ██╗██████╗ ██████╗ ██╗  ██╗██╗   ██╗
 ██╔════╝██║  ██║██╔══██╗██║██╔════╝    ████╗ ████║██║   ██║██╔══██╗██╔══██╗██║  ██║╚██╗ ██╔╝
 ██║     ███████║██████╔╝██║███████╗    ██╔████╔██║██║   ██║██████╔╝██████╔╝███████║ ╚████╔╝ 
 ██║     ██╔══██║██╔══██╗██║╚════██║    ██║╚██╔╝██║██║   ██║██╔══██╗██╔═══╝ ██╔══██║  ╚██╔╝  
 ╚██████╗██║  ██║██║  ██║██║███████║    ██║ ╚═╝ ██║╚██████╔╝██║  ██║██║     ██║  ██║   ██║   
  ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚══════╝    ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝   ╚═╝   
 `;

  export const LIPSUM = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam scelerisque felis et justo porttitor, id pellentesque erat dignissim. Nulla volutpat non augue non tincidunt. Vivamus sit amet lorem venenatis, eleifend nunc in, venenatis nibh. Praesent sodales laoreet lectus, a gravida tortor tincidunt tempor. Duis in ornare eros. Phasellus magna lacus, imperdiet sed tempor vitae, porttitor vitae dui. Donec et sapien eget magna dapibus lobortis. Integer in ligula diam. Duis et cursus nunc. Cras gravida, diam non interdum ullamcorper, libero turpis commodo enim, ut faucibus justo nisi at lectus. Donec vel vulputate purus, ut efficitur elit. Cras odio augue, ultricies auctor venenatis sit amet, molestie ac velit. Mauris non luctus felis. Nullam semper posuere urna non rhoncus. Donec id enim iaculis, tempor justo id, finibus dui. Pellentesque ut feugiat nulla.

  Quisque vel enim non dui elementum suscipit. Aliquam lobortis cursus neque, eu commodo tellus ullamcorper id. Donec eu dignissim metus. Quisque porta varius dui, sit amet venenatis neque. Pellentesque faucibus risus a risus commodo euismod. Donec at euismod urna. Mauris sed egestas est. Nunc risus sem, placerat a commodo eu, tincidunt pellentesque nulla. Suspendisse potenti. Donec malesuada, nisi sit amet finibus hendrerit, massa elit cursus magna, a tristique neque massa at massa. Praesent euismod pulvinar neque, eget placerat arcu pharetra nec. Nunc sagittis laoreet aliquet. Sed purus erat, finibus at nulla et, sagittis ornare risus. Duis facilisis efficitur risus, at tempus odio lobortis et.
  
  Mauris lacinia erat mi, quis pulvinar magna aliquet ac. In blandit tempor posuere. Nulla facilisi. Vestibulum dapibus vestibulum tellus, varius tempus odio molestie et. Aenean imperdiet ullamcorper sem interdum condimentum. Sed lacinia hendrerit consequat. Fusce elementum ultricies eros, ut efficitur mauris molestie nec. Proin commodo massa sed auctor tincidunt. Aliquam id lorem in massa vehicula rhoncus et ut eros.
  
  Proin non urna ut tortor congue tempor. Integer at semper ex. Nulla in orci scelerisque orci varius egestas. Quisque tellus justo, interdum sit amet arcu ut, dapibus consectetur nunc. Integer non enim sit amet magna facilisis malesuada. Morbi finibus nunc ut arcu ultricies suscipit. Nullam sed dui sit amet massa lacinia pretium. Nullam lacus arcu, consequat at neque quis, viverra sollicitudin sem. Etiam porta, elit ac dignissim hendrerit, ligula lectus dapibus nisi, quis aliquam justo risus nec magna. Pellentesque elementum interdum libero quis rutrum. In pretium diam ut faucibus gravida. Pellentesque at ante tempus, dignissim ipsum at, viverra purus. Aenean ut auctor sem.
  
  Quisque fringilla nisi vitae odio hendrerit, vitae scelerisque dolor blandit. Nunc scelerisque arcu et augue porta accumsan. In lacinia vitae ex quis consectetur. Maecenas eu pulvinar diam. Sed ultricies ut nibh sed auctor. In gravida accumsan lacus nec tempus. Maecenas porttitor volutpat nisl a sodales. Vestibulum in mauris placerat, rhoncus turpis blandit, lobortis tellus. Cras et ipsum vel justo feugiat ultricies vitae quis nisl. Donec turpis metus, tincidunt vitae arcu in, varius imperdiet justo. In metus ex, condimentum quis lacinia a, faucibus sit amet turpis.
  
  Quisque tincidunt, turpis porttitor accumsan porttitor, nisi ligula congue metus, in congue purus leo at sapien. Fusce nisi odio, molestie sit amet vestibulum id, viverra et dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed commodo, dolor ut porttitor eleifend, est magna blandit leo, sit amet egestas tellus leo et neque. Nulla malesuada maximus enim ut condimentum. Nulla at tellus volutpat, finibus massa non, euismod tellus. Sed imperdiet rutrum massa in dictum. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis accumsan nisi quis risus rhoncus, at fringilla justo consectetur. Curabitur ac velit varius, sodales nisi vitae, bibendum nunc. Praesent ac pharetra nulla. Vestibulum laoreet pulvinar fringilla. Fusce imperdiet sodales nulla quis vestibulum.
  
  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur imperdiet, ligula sed sagittis laoreet, est neque ullamcorper enim, eget vehicula ligula tellus sed lorem. Integer vulputate nulla vel ante dictum, rhoncus hendrerit est maximus. Pellentesque dapibus neque nisl, vitae finibus tellus imperdiet condimentum. Nulla interdum cursus nibh, sed suscipit neque molestie a. Quisque porttitor elit eu urna luctus suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam non tellus ornare, rhoncus sapien id, vulputate metus. Vestibulum dignissim mi vitae lacus tincidunt consectetur. Curabitur dictum, ante a dictum varius, dolor nulla gravida erat, vel porttitor leo quam ac augue. Quisque pharetra id quam sed laoreet. Integer eu felis elit. Sed vitae purus vitae neque gravida rutrum a eget ligula.
  
  Nulla ullamcorper ullamcorper justo sit amet vulputate. Quisque et ultrices velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut ac dui laoreet, ullamcorper risus vel, condimentum mi. Pellentesque sollicitudin diam quam. Curabitur ut cursus enim. Pellentesque sit amet felis nibh. Pellentesque ultrices, purus suscipit sodales bibendum, purus lorem mollis quam, vitae egestas arcu justo ut diam. Nullam lobortis fermentum aliquet. Duis et finibus massa.
  
  Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris ut eros tellus. Nullam sodales, tellus vitae mattis malesuada, sapien odio sollicitudin nisl, eget laoreet dolor ligula et nulla. Donec placerat erat quis erat congue, sed auctor elit hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum aliquet tristique odio, eu dignissim tortor ornare ut. Morbi hendrerit maximus mauris vel pellentesque.
  
  Curabitur faucibus massa velit, tempus maximus sapien rhoncus sit amet. Vestibulum sed commodo orci, rhoncus malesuada enim. Vestibulum luctus odio at erat porta, nec viverra leo porttitor. Sed iaculis lacus vitae dolor dignissim gravida. Morbi eget interdum nisi, a egestas massa. Morbi cursus congue elit et varius. Nulla quis odio vestibulum, fermentum elit quis, tincidunt ipsum. Duis erat massa, mollis ut pellentesque et, sodales a nulla. Etiam sit amet odio id ante tempor dignissim. Proin facilisis euismod quam in lobortis. Praesent feugiat magna id sem rhoncus, a semper purus interdum.
  
  Aliquam erat volutpat. Proin ullamcorper leo ligula, et venenatis lectus laoreet in. Duis sit amet mauris consequat, euismod lacus non, consequat orci. Maecenas gravida dignissim massa, quis mattis neque tincidunt eget. Suspendisse ut massa erat. Quisque sodales eros eget elit congue aliquet. Donec scelerisque ligula non tellus malesuada viverra. Vestibulum luctus gravida ipsum, vitae mattis dui posuere at. Sed rhoncus suscipit quam ut iaculis. Suspendisse fringilla justo lectus, id consectetur lorem blandit non. Vivamus egestas ligula quis leo pharetra, id ultrices est placerat. Morbi et dignissim ipsum. Proin venenatis massa id nibh vestibulum vehicula. Fusce at dignissim leo. Vivamus vitae ullamcorper nulla.
  
  Cras consequat condimentum elementum. Pellentesque egestas dui quis dui tempus, vel varius nibh molestie. Aenean non dolor elementum turpis finibus mattis. Cras blandit sodales augue non gravida. Duis ornare nunc mollis nibh scelerisque, id feugiat ante faucibus. Donec ullamcorper, libero commodo consectetur feugiat, quam sapien tincidunt urna, eu lacinia lacus mauris at turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus augue quam, egestas in lacus non, tincidunt luctus neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas posuere orci sed mauris pulvinar, vitae imperdiet magna auctor.
  
  Nulla accumsan lorem sit amet justo gravida, nec congue arcu venenatis. Mauris quis dapibus ipsum, id mattis felis. Curabitur placerat purus mi, quis tempus justo mollis sit amet. Nam pellentesque ultrices neque, non interdum sapien laoreet et. Pellentesque ex arcu, feugiat vel nisi eget, rhoncus egestas felis. Praesent lacinia dolor vel scelerisque finibus. Vivamus luctus tortor at lacus ullamcorper congue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla tristique nunc in eros egestas, ac egestas magna tristique.
  
  Nullam consectetur pharetra interdum. Aenean aliquam suscipit urna in porttitor. Mauris rutrum dui ut risus varius eleifend. Phasellus eget fringilla tortor. Aliquam tristique sapien dui, et suscipit nibh sagittis vitae. Vestibulum nec gravida nisl. Phasellus eu turpis id enim fringilla congue eget id ante. Fusce rutrum, magna eget maximus pretium, risus erat sollicitudin quam, interdum viverra lorem risus ac velit. Vivamus a risus risus. Phasellus vel blandit quam, sit amet finibus neque. Ut eget magna ut velit aliquam lobortis eu vitae risus. Nam interdum felis nec ipsum convallis, non aliquam justo imperdiet. Etiam tristique nulla sit amet congue porta. Cras quam augue, porttitor et purus at, dictum efficitur ex.
  
  Pellentesque dapibus lectus dolor. Aenean imperdiet vulputate placerat. Fusce sagittis ipsum neque, a ultricies magna consequat id. Ut auctor sed velit vitae porttitor. Mauris nisi justo, commodo vel odio ac, tincidunt mollis lectus. Nam consequat, turpis sit amet finibus imperdiet, orci dolor volutpat dolor, ac consectetur nisl urna id tellus. Aenean eros enim, placerat vitae sem ac, porta rhoncus felis. Fusce convallis varius nisi, non blandit magna elementum quis. Proin fermentum quis lectus non feugiat. Morbi ultrices, ante non gravida maximus, lacus nunc volutpat magna, eget blandit augue dui vel nisl. Quisque congue urna quis molestie egestas. Nulla eget porttitor dolor. Maecenas enim nisl, venenatis et euismod a, hendrerit vitae enim. Sed et justo consequat, vehicula massa ornare, malesuada ligula.`
  